# Generated by Django 4.2 on 2023-05-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_review_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='arv_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
